### ISSUE TITLE
Password Hashing

### ISSUE THREAD

**Issue by suneettipirneni** [Imageus-OSS/server#27]
Hash passwords on user create and validate hash on login.

**Comment by Armintron** [comment]
Passwords are hashed on the frontend, not the backend. Unhashed passwords should never be sent over the internet.

**Comment by suneettipirneni** [comment]
> Passwords are hashed on the frontend, not the backend. Unhashed passwords should never be sent over the internet.

No, hashing *should always be done* in the backend. If you hash in the front end, the de-facto password just becomes the hashed password, it provides no extra security. As for your concern about transmitting cleartext passwords across the internet, we are using SSL or HTTPS which encrypts requests that sent across the internet automatically.

**Comment by Armintron** [comment]
I see, thanks for clearing that up.
